### ISSUE TITLE
Add namegen command option to output available name lists

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#14]
Modify the `namegen` command so that, when passed the argument `-l`, it doesn't output names and instead outputs a list of the available name lists, one on each line.

The output should look like this:

```
english
spanish
```

**Comment by p4rsec** [comment]
I'd be interested in implementing this. Are you looking for it to read the name-list files and show whatever is in the main directory, or are you looking for it to be a static list of names?

**Comment by BenOvermyer** [comment]
Just making it static will satisfy this PR. Something more clever, like dynamically figuring out what name lists are available, is interesting but not necessary yet.

**Comment by p4rsec** [comment]
Gotcha, sounds good.

**Comment by p4rsec** [comment]
I'm failing to get the code to compile. I'm not totally familiar with how go works as far as packages and such. I tried changing my `$GOPATH`, I tried moving the repo into `$HOME/dev/go/src/github.com/[etc]`, I tried running `main.go` directly... etc. Now it's complaining that `namegen` is undefined on line 33:15 of `main.go`. Is this just me borking it up?

**Comment by BenOvermyer** [comment]
If your `$GOPATH` is `$HOME/dev/go`, then the repo should be in `$HOME/dev/go/src/github.com/ironarachne/namegen`.

How are you compiling? Are you using the `build.sh` file in the root directory?

**Comment by p4rsec** [comment]
Yep! Still showing some weirdness. Could still be that I messed something up. Should I be calling `flag.Parse()` after both flag declarations or is it fine to have just stuck my declaration under you first one? I would've expected it to just work, but maybe I confused the compiler that way.
![screen shot 2018-10-03 at 3 35 15 pm](https://user-images.githubusercontent.com/15082726/46434590-0b778d80-c722-11e8-9da3-1dfb120daa7e.png)

**Comment by p4rsec** [comment]
Wait, I figured what broke it. Somehow I accidentally put an underscore before the path of `namegen`. Opps.

**Comment by BenOvermyer** [comment]
Haha, no worries. Glad you got it sorted out.
