### ISSUE TITLE
Separate out male and female names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#26]
Each name list should be split out into male and female slices for given names.

The `namegen` command should allow for generating only male or only female names.

**Comment by eonmilu** [comment]
I'll do this!

**Comment by IamRaviTejaG** [comment]
@BenOvermyer I can work on this issue. Please let me know where to get started? Like, all the modules have a list of first and last names, should I begin with sorting things manually, and then make two more lists, etc? Or should this issue be approached in a different way?

**Comment by BenOvermyer** [comment]
@IamRaviTejaG Yes, you'd have to manually break apart the `firstNames` and `lastNames` slices from each language file. At this point, it might be best to create a struct-based pattern. Something like this:

```go
// in namegen.go
type NameSet struct {
    maleNames []string
    femaleNames []string
    lastNames []string
}

// in englishnames.go
var (
    englishNames = NameSet{maleNames: []string{"bob", "joe"}, femaleNames: []string{"alice", "lisa"}, lastNames: []string{"smith", "jones"}}
)
```

**Comment by mukulrawat1986** [comment]
I made the PR for Icelandic names earlier, I scraped the names separately and then sorted them into one list, so maybe, later on, I can undo that, and separate out the male and female first names. I will send a PR in a bit.
