### ISSUE TITLE
Divide Thai names into male and female

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#34]
The Thai names need to be divided up into male and female first names.

**Comment by kittinan** [comment]
Hello @BenOvermyer 

I will help you to classify Thai names into male and female but I have no experience with Go lang.

**Comment by kittinan** [comment]
Some name can be both male and female, How can I solve it?

**Comment by BenOvermyer** [comment]
@kittinan If you can split the first names into male and female lists, that would be enough. If some names can be both, they should be in both lists.

I will take care of the Go part.

**Comment by kittinan** [comment]
@BenOvermyer OK, I will do this issue this weekend
