### ISSUE TITLE
Add Portuguese names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#47]
Add Portuguese names to the project.

**Comment by BenOvermyer** [comment]
Possibly useful: https://github.com/joaoalvarenga/namegenderclassifier/blob/master/data/nomes.csv

**Comment by DireWolf707** [comment]
Hye, I am new to open source and want to contribute to this issue for hacktoberfest.
Can you assign me this issue?

**Comment by BenOvermyer** [comment]
Sure thing. Just remember to submit your PR after October 1!

**Comment by DireWolf707** [comment]
What are the minimum and maximum no. of names(per gender) required?

**Comment by BenOvermyer** [comment]
At least twenty would be good. At least fifty would be ideal.
