### ISSUE TITLE
Add Chinese names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#48]
Add Chinese names to the project.

**Comment by BenOvermyer** [comment]
Possibly useful: https://github.com/wainshine/Chinese-Names-Corpus/tree/master/Chinese_Names_Corpus

**Comment by semi-infiknight** [comment]
please assign me this issue

**Comment by NevilleMthw** [comment]
Is this issue available?

**Comment by BenOvermyer** [comment]
@NevilleMthw Yes, the previous assignee backed out. It's all yours!

**Comment by Maahipal27** [comment]
@BenOvermyer Please assign me this issue.I would like to work on this issue

**Comment by BenOvermyer** [comment]
@Maahipal27 Done.

**Comment by Maahipal27** [comment]
@BenOvermyer I have made the PR please review it.
