### ISSUE TITLE
Add Hindu names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#49]
Add Hindu names to the project.

**Comment by rSrikesh** [comment]
My name is Srikesh and I am from India . Can i look into this issue ?

**Comment by DireWolf707** [comment]
Is this issue taken or can I craete a pull request for this issue until tomorrow's hacktoberfest ?

**Comment by BenOvermyer** [comment]
@DireWolf707  Someone else has done this work and is just waiting until tomorrow to submit a PR.
