### ISSUE TITLE
Add Spanish names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#5]
Add Spanish names. 

This will require:

* Creating a file `spanishnames.go` with two arrays, `spanishFirstNames` and `spanishLastNames`
* Adding a block to the if statement in `namegen.go`'s `GetNamesByType` function for Spanish

**Comment by alvaromontoro** [comment]
I could help with this. 
Are you looking for most common names? Also, how many would you want?

**Comment by BenOvermyer** [comment]
@alvaromontoro I've merged one PR for this, but if you want to add more, that'd be great. Any amount works, but the more there are, the better.

**Comment by alvaromontoro** [comment]
@BenOvermyer it seems that they have added a bunch, but I will clean the list and add a few more (specially last names, as the ones in the list mostly start with the letter A). I will create a PR to add more if it's ok

**Comment by BenOvermyer** [comment]
Sure, that's fine.
