### ISSUE TITLE
Add Swedish names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#50]
Add Swedish names to the project.

**Comment by BenOvermyer** [comment]
For first names this looks useful: https://github.com/bolddp/swedish-names

**Comment by rSrikesh** [comment]
i will look into this issue

**Comment by BenOvermyer** [comment]
@rSrikesh Acknowledged. If you're doing it for Hacktoberfest, remember to wait to submit your PR until after October 1!
