### ISSUE TITLE
Add Norwegian names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#53]
Add Norwegian names to the project.

**Comment by BenOvermyer** [comment]
Possibly useful: https://github.com/meklitAIA/norsk-names/tree/master/data

**Comment by tplive** [comment]
I'm assuming you want a list of *typical* norwegian names, not just any? It think the names should be recognized by norwegians as norwegian names, lest there wouldn't be much point in calling the list norwegian names? :)

**Comment by BenOvermyer** [comment]
@tplive Yeah, that's right, haha.

**Comment by tplive** [comment]
@BenOvermyer well, I'll have a PR ready for you on October 1st.. 😉
