### ISSUE TITLE
Add Maori names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#54]
Add Maori names to the project.

**Comment by BenOvermyer** [comment]
Possibly useful: https://www.waikato.ac.nz/library/resources/library-publications/index-of-maori-names

**Comment by NevilleMthw** [comment]
Can I do this issue? @BenOvermyer

**Comment by BenOvermyer** [comment]
Go right ahead.

**Comment by NevilleMthw** [comment]
Hi @BenOvermyer, it does not look like the link for the Maori names are categorized by gender so maybe another link may be better?
[Maori names](https://www.schoolmykids.com/parenting/baby-names/maori-baby-boy-names-with-meaning) one link I found but not as exhaustive compared to the Waikato link. But it is categorized by gender.

[Maori Surnames](http://whakapapa.org.nz/whakapapa/surnames-all.php?tree=) another link for surnames. Would this be okay?

**Comment by BenOvermyer** [comment]
@NevilleMthw Yes, those are fine.
