### ISSUE TITLE
Add Mayan names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#57]
Add Mayan names to the project.

**Comment by BenOvermyer** [comment]
A list of Yucatec Mayan surnames:

AB
ABAN
ABNAL
AC
AIL
AKE
AKHOLAY
AYI
AYIL
AYL
BA
BAA
BACAB
BACAL
BAK
BALAM
BALCHE
BAS
BATAN
BAZ
BE
BIL
BOLON
CAACH
CAB
CABICH
CACH
CAHUM
CAL
CAMAL
CAMSAL
CAN
CANCHE
CANTE
CANTUN
CANUL
CAT
CATZIM
CAUICH
CAYUT
CEH
CEL
CELIZ
CEME
CEN
CETZ
CETZAL
CI
CIAN
CINE
CITUK
CIYAU
CITUM
COB
COBA
COBOH
COCHUAH
COCOM
COH
COL
COOB
COOL
COPO
COT
COUOH
COX
COYI
CACAB
CUITUM
CULUA
CUMII
CUMUX
CUPUL
CUTZ
CUXIM
CUY
CUYTUM
CHAB
CHABLE
CHALA
CHALE
CHAN
CHAY
CHE
CHEL
CHI
CHII
CHICIL
CHICLIN
CHICMUL
CHIM
CHIMAL
CHINAB
CHOBEN
CHOO
CHUAN
CHUC
CHUIL
CHUL
CHULIM
CHUNAB
CHAY
DZACAB
DZAHE
DZAL
DZAY
DZIB
DZUL
EB
EITUK
EK
EUAN
EX
EZ
HA
HABAN
HABNAL
HAU
HE
HOMA
HUCHIM
HUH
HUMAN
HUN
ICH
ICTE
IDZ
IDZINCAB
INCAB
ITZA
IUIT
IZ
JUCHIM
KAAK
KAK
KANCAB
KANTUN
KANXOC
KAUIL
KE
KEB
KETZ
KEUEL
KINICH
KINIL
KOH
KU
KUK
KUMAN
KUTZ
KUZEB
KUXIM
KUYOC
KAYTUN
MAAZ
MAC
MAL
MAS
MATU
MAZ
MAZTE
MAZUM
MAZUN
MEX
MIAM
MIAN
MIZ
MO
MOAN
MOH
MOO
MUAN
MUCUY
MUKUL
MUL
MUT
MUTAL
MUUL
MUY
NA
NAAL
NABTE
NACAN
NAH
NAL
NAUAT
NAY
NAYAL
NIC
NOH
NUCH
OCH
OXTE
OY
PACAB
PALIB
PAN
PANTI
PAT
PAUO
PECH
PET
PEU
PEZ
PIB
PITZ
PIX
POL
POMOL
POOT
POT
POX
PUC
PUCH
POOC
PPENCEH
PPEZTE
PPOL
TA
TACU
TAH
TAMAY
TAX
TAYUTE
TEC
TEP
TEPAL
TINAALTO
TO
TOMAT
TOO
TOX
TUC
TUCUCH
TUIN
TULUM
TUN
TUT
TUTUL
TUYU
TUZ
TZAB
TZABNAL
TZAKUM
TZAMA
TZEK
TZEL
TZIU
TZOTZ
TZUC
TZUL
TZUM
UACAL
UC
UCAN
UCHIM
UECH
UEUET
UEXUH
UH
UHE
UICAB
UITZ
UITZIL
ULAK
ULUAC
UMAN
UN
UX
UXUL
UZ
XAMAN
XAMANCAB
XICUM
XUI
XIX
XOC
XOL
XOOL
XUCH
XUL
XULUC
YA
YAA
YAH
YAM
YAMA
YE
YIX
YOC
YTZA
YTZAB
YUAN
YUIT
YUPIT
YX
ZACNAL
ZAK
ZALU
ZEL
ZIMA

**Comment by LuisFerTR** [comment]
Hi, I can work on this if it's still available :D

**Comment by BenOvermyer** [comment]
Go for it.
