### ISSUE TITLE
Add Icelandic names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#6]
Add Icelandic names.

This will require:

* Creating a file names.go with two arrays, icelandicFirstNames and icelandicLastNames
* Adding a block to the if statement in namegen.go's GetNamesByType function for Icelandic

**Comment by mukulrawat1986** [comment]
Hi, I would like to work on this.

**Comment by mukulrawat1986** [comment]
I have made a PR, please review it.

**Comment by mukulrawat1986** [comment]
#23

**Comment by mukulrawat1986** [comment]
#23
