### ISSUE TITLE
Add Polish names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#79]
Add Polish names to the generator.

See https://en.wikipedia.org/wiki/Polish_names

**Comment by DireWolf707** [comment]
If no one is already doing this.
Pls assign

**Comment by RaturiAR7** [comment]
@BenOvermyer  Though my previous PR is not appearing in my profile I would like to contribute to this issue. Maybe this time it might showup in the profile. Please assign me this issue if no one is working on this.

**Comment by BenOvermyer** [comment]
@RaturiAR7 Sure, all yours. I'm still mystified as to why your last PR is not showing up for Hacktoberfest.

**Comment by RaturiAR7** [comment]
@BenOvermyer please review, I made a pull request.
