### ISSUE TITLE
Add Ukrainian names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#80]
Add Ukrainian names to the generator.

See https://en.wikipedia.org/wiki/Ukrainian_name

**Comment by BenOvermyer** [comment]
This one has a completed PR ready, but I won't be merging it until after October 1 so it counts for Hacktoberfest.

**Comment by Hopeah** [comment]
So sorry, didn't realize! Thank you for letting me know. Will open it up on the weekend. If you could assign this one to me, I would appreciate it!
