### ISSUE TITLE
Add Irish names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#83]
Add Irish names to the generator.

See https://en.wikipedia.org/wiki/Irish_name

**Comment by NevilleMthw** [comment]
Hi, are the names in that link enough or would https://en.wikipedia.org/wiki/List_of_Irish-language_given_names be better?

Thanks,
Neville

**Comment by NevilleMthw** [comment]
Oh okay, I have never participated in the event before but I guess I will just submit the PR on October 1st which would count towards the contribution.

**Comment by NevilleMthw** [comment]
@BenOvermyer For the Irish names, do you want only the native names of both genders or the foreign ones as well?

**Comment by BenOvermyer** [comment]
Native, preferably.

**Comment by NevilleMthw** [comment]
Do you need Irish last names? If so, I found a link: [Irish Gaelic Surnames](https://sites.rootsweb.com/~irlkik/ihm/irenames.htm). Let me know if this is fine or not needed.

**Comment by BenOvermyer** [comment]
@NevilleMthw Yeah, last names are needed. Good link!

**Comment by NevilleMthw** [comment]
Hi @BenOvermyer, I have one question on how you convert each name to a string in your variables since I am not too familiar with Go syntax. The last names list is quite long and it would be difficult to convert each name to a string.
