### ISSUE TITLE
Add Hawaiian names

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/namegen#86]
Add Hawaiian names to the generator.

See https://en.wikipedia.org/wiki/Hawaiian_name and https://en.wiktionary.org/wiki/Appendix:Hawaiian_given_names.

**Comment by semi-infiknight** [comment]
please assign me this issue

**Comment by ArshErgon** [comment]
is it okay, if I work on it?

**Comment by BenOvermyer** [comment]
Go ahead, it's fair game.
